# Generated by Django 3.0 on 2019-12-16 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bugtracker.BaseModel')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
            bases=('bugtracker.basemodel',),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bugtracker.BaseModel')),
                ('display_text', models.CharField(max_length=50)),
                ('is_open', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            bases=('bugtracker.basemodel',),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bugtracker.BaseModel')),
            ],
            bases=('bugtracker.basemodel',),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bugtracker.BaseModel')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2000)),
                ('created_by', models.IntegerField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bugtracker.Project')),
                ('ticket_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bugtracker.Status')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bugtracker.TicketType')),
            ],
            bases=('bugtracker.basemodel',),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bugtracker.Status'),
        ),
    ]
